vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /proyecto-semestre-grupo-3/pets-project/public/images/animals
            upload_destination: '%kernel.project_dir%/public/images/animals'

