vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    
    mappings:
        product_image:
            uri_prefix: /images/ads
            upload_destination: '%kernel.project_dir%/public/images/ads'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true